Members-only
emmanuellekamwa/members-only pull request #1
Opened 2021-02-18 16:55 UTC by emmanuellekamwa

In this project, I have made use of:
- Devise gem for user authentication
- Rubocop and stylelint to correct linter errors

2021-02-18 20:32 UTC, whiz25 requested changes
## Invalid PR 😞 
Hey @emmanuellekamwa thanks for putting efforts into building this app. I can not however, review this PR because it lacks results for the build process from github actions. 

I also see that you have the `linters.yml` file in the `.github` folder but the build process was not triggered. What could be the problem? Please make sure the build is triggered and all cases pass. Checkout this [article](https://gorails.com/episodes/github-actions-continuous-integration-ruby-on-rails) for ideas.
Also, this PR is appearing as a re-review but I see no previous reviews. Is it possible that you created a new PR? All re-reviews must be made from the first PR created for the project. That is important for reference for other TSE's reviewing the same project.


### Martin Afani

2021-02-19 07:07 UTC, emmanuellekamwa commented
Good morning. I have created a new repository and a new pull request that's
why you are not seeing previous reviews

Le jeu. 18 févr. 2021 à 21:33, Afani Martin <notifications@github.com> a
écrit :

> *@whiz25* requested changes on this pull request.
> Invalid PR 😞
>
> Hey @emmanuellekamwa <https://github.com/emmanuellekamwa> thanks for
> putting efforts into building this app. I can not however, review this PR
> because it lacks results for the build process from github actions.
>
> I also see that you have the linters.yml file in the .github folder but
> the build process was not triggered. What could be the problem? Please make
> sure the build is triggered and all cases pass. Checkout this article
> <https://gorails.com/episodes/github-actions-continuous-integration-ruby-on-rails>
> for ideas.
> Also, this PR is appearing as a re-review but I see no previous reviews.
> Is it possible that you created a new PR? All re-reviews must be made from
> the first PR created for the project. That is important for reference for
> other TSE's reviewing the same project.
> Martin Afani
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/emmanuellekamwa/members-only/pull/1#pullrequestreview-593620918>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOTSG77IT2CLA6LZIMV7ZYTS7V2QPANCNFSM4X2UYUOA>
> .
>

2021-02-19 15:41 UTC, descholar-ceo requested changes
# Status: Invalid Submission :x: :disappointed: :stop_sign: 
## Hello @emmanuellekamwa   :handshake: :handshake: :handshake: 

Thank you for submitting a code review request. And congratulations on that you have completed this project. However your code review request is marked as invalid due to the following reasons:

1. The submitted Pull Request appears to be a re-review, but I can't seem to find previous review feedback, so I cannot review this PR because I cannot start from scratch as I should be doing the re-review. I understand that you created a new repository , but why did you do that? Was it needed? Could you submit the Pull Request where you got the previous review(s) and if it has some issues, list them out and ask for help instead ofm submit a new fresh project

Happy coding!!!
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-02-19 18:29 UTC, MahmoudBakr23 requested changes
# **Changes Required 🛑♻**

<hr>

Hello there, great job you've done so far on this project. However, there are still a few changes to make in order to get it approved 😊🙏

- [ ] Kindly adjust your routes Posts controller (You mistyped Posts into Post) Please fix that!
- [ ] A logged_in user can see every post's author. Currently, I cannot see that implemented!
![posts_index_requirement](https://user-images.githubusercontent.com/47625407/108545689-c7848380-72f0-11eb-81c9-9b4eabc36164.png)

- [ ] Please put any large (un-related) files to ```.gitignore``` file (There is more than 5000+ files to review here) This is too large.
- [ ] Please adjust your README file and add the rest of the setup locally steps i.e. ```rails db:create``` and ```rails db:migrate```

<hr>

Kindly do these changes before asking for another re-review.
Good luck and happy coding 👨‍💻

2021-02-22 17:16 UTC, whiz25 requested changes
## Changes Required 🙏🏿 
Nice work on the requested changes. I was able to sign up, see post author and log out. Well done.
We however, need to fix the README file. There's a lot of instructions missing in the 'Getting started' section of the page.
Check my comments for suggestions on how to update the README file.


### Martin Afani

2021-02-22 17:16 UTC, whiz25 commented on README.md
> +- First clone the git repository into your local machine
- How does one clone the repo? Add explicit commands for doing that.

2021-02-22 17:16 UTC, whiz25 commented on README.md
> +- Run bundle install
- What do you mean by 'Browse into the repository'? Do not leave room for guesses because it would lead to confusions for those who want to contribute to this project.

2021-02-22 17:16 UTC, whiz25 commented on README.md
> +# Show some support
- add a section for contributing to this repo. use this [template](https://github.com/microverseinc/readme-template) for reference.

2021-02-22 17:16 UTC, whiz25 commented on README.md
> +- Sign_up to create a new user, create a new post and log out when you are done
- Change this to `Sign up`. `Sign_up` looks like a variable name.

2021-02-23 11:52 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Emmanuelle Alix** 
Nice job so far :muscle:  :muscle:
Your project meets most of the requirements :clap: :clap: :clap:  
Just one last detail to improve before you can go ahead:

- [ ] According to Odin Project instructions, you must restrict access to "new" and "create" methods by creating a helper method (in application_helper).
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-02-23 14:42 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @emmanuellekamwa**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] I can see that you create d the helper method requested by the previous code reviewer, but you haven't used it anywhere. please make sure to implement the requested feature by using the method.


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2021-02-24 10:28 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @emmanuellekamwa  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding


# [Required Changes] :red_circle: 
- [ ] You have some logic in views: View-related logic can be encapsulated in View helpers (app/helpers/*_helper.rb)
  - [ ] There shoud be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it. [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright _=> To make sure that I clarify what you need to change on this reqirement: Ensure that there is no if conditions, and no loops in your view (`.html.erb`) files_
  
#### Resources to help you learn about this:

- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code/)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-02-24 14:34 UTC, oloomoses approved these changes
#  Congratulations, Project Approved! :tada: :muscle: :clap: 

Congratulations on making all the requested changes and getting this project approved. :+1: 

You can now merge this branch and go on with your next project.

:bulb: Do not forget to submit your project completion form after merging this branch.

I wish you the best,
Oloo Moses

2021-02-24 14:43 UTC, merged